### PR TITLE
Implementing snapshot

### PR DESCRIPTION
**Pull request by antoniocfdsilva**

### CODE REVIEW

**Comment by kakashidinho** [comment]
Thanks for the PR. I will take a look later when I have time.

**Comment by antoniocfdsilva** [comment]
> Thanks for the PR. I will take a look later when I have time.

Any news about this PR?

**Comment by kakashidinho** [comment]
> > Thanks for the PR. I will take a look later when I have time.
> 
> Any news about this PR?

Thanks for the PR again. To be honest, I have updated the framework to make it cross platform across iOS and macOS. So MGLKView now is a macOS class as well (the xcode project now can build both mac and iOS versions). So putting UIImage here is not going to be compiled on mac since it is iOS only class.

It is possible to change the return type to CGImage instead of UIImage to make it compilable on both iOS and mac. But honestly I think this feature could be moved outside MetalANGLE.framework. You can put it in your application code instead of inside MetalANGLE view. Since glReadPixels() can be called anywhere.

Anyway, may I know about the application you are working on. I’m very happy that MetalANGLE is helpful for your work.

**Comment by kakashidinho** [comment]
Close this as the new commit [1b9ddf75b](https://github.com/kakashidinho/metalangle/commit/1b9ddf75b4d28f6d0311457ea551d393595307cd) has implemented this snapshot function for iOS. I decided to include this feature after noticing that the original Apple's GLKView also has it.

**Pull request closed without merging**
