### PR TITLE
HDPI scaling fix

### PR DESCRIPTION
**Pull request by elix22**

### CODE REVIEW

**Comment by kakashidinho** [comment]
wow, thanks. Looks like legit bug. Do you have a way to reproduce this issue?
I thought the surface would automatically resize itself on next presentation if it detects odd size difference.

**Comment by elix22** [comment]
You can reproduce it on my master branch 

https://github.com/elix22/Urho3D

Just comment/uncomment this fix and run one of the samples on iOS device ( cmake_ios_metal.sh ) .
One of below will do 
56_MaterialEffects
69_OffroadVehicle

**Comment by kakashidinho** [comment]
I cloned your repo, removed your fix and the examples still worked. Probably the auto resize already handled this issue. You might encounter the issues when using an older version of MetalANGLE.

**Comment by elix22** [comment]
Hmm ..
I am actually quite sure I encountered this issue with your latest MetalAngle .

**Comment by kakashidinho** [comment]
I debugged, even if the size was not correctly set in `SurfaceMtl::initialize()`, it got correctly resized the first time there is a draw command happened. See `SurfaceMtl::obtainNextDrawable`: https://github.com/kakashidinho/metalangle/blob/bf63ede8da61a36ba04da99c7ec13a5bce4be23c/src/libANGLE/renderer/metal/SurfaceMtl.mm#L618
Maybe do a clean clone and verify again.

**Comment by kakashidinho** [comment]
anw, don't mind the CI errors. It looks like travis CI is not free anymore, and Appveyor updated the macOS image and it is not compatible with the current gn script anymore.

**Comment by elix22** [comment]
Hmm ...
strange
It's reproducible on my devices .

Took some screenshot
https://drive.google.com/file/d/1HIiby-q6hxAY2Ug_rI0bfLEGmyJBzesj/view?usp=sharing

SurfaceMtl::obtainNextDrawable is called .
checkIfLayerResized(context) returns true 
however it's not updating the viewport

**Comment by kakashidinho** [comment]
OK, thanks. I missed the comment that you said the issues was noticed on iOS (I tested on macOS and didn't see the issue).
Closed this as I adopted your fix here https://github.com/kakashidinho/metalangle/commit/cb39155cdb7b5258d503ac094008caa0959ba4bc

**Comment by kakashidinho** [comment]
On macOS, Urho already manually set the correct viewport by the time the first draw happened.

**Comment by kakashidinho** [comment]
Btw,
It's nice that you are still working on Urho3D regularly.
Wonder how that project is going to move forward. The forums seem to have too much politic nowadays that I have to quit long time ago.

**Comment by elix22** [comment]
I am working on my own branch , I don't mind the politics  , it doesn't affect my development .
Actually I quit my day work this year , I am going to rest and relax this year ,  so I have more time now working on my pet projects  .

I Have been working on a Urho.Net C# cross platform solution (your metal backend is also part of it )
I might write some small  mobile iOS/Android game based on it

https://github.com/elix22/Urho.Net
https://discourse.urho3d.io/t/urho-net-c-cross-platform-game-development-framework/6674

**Pull request closed without merging**
